# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
